### PR TITLE
designed the login page and revamped the signup page

### PR DESCRIPTION
**Pull request by redfyel**

### CODE REVIEW

**Comment by narainkarthikv** [comment]
Hi @redfyel. There's a merge conflict here. Can you resolve it and PR

**Comment by narainkarthikv** [comment]
image

There are merge conflicts. Please pull the latest changes from the repository, merge them into your current branch, resolve any conflicts, and submit a pull request.

**Comment by redfyel** [comment]
Yes..will work on it

**Comment by redfyel** [comment]
please look into now!

**Pull request merged**
